---
name: kibana
version: 0.1.5
description: Sample chart template for registry
keywords:
- kubernetes
- logging
- data
- elasticsearch
- kibana
home: https://github.com/samsung-cnct/chart-kibana
sources:
- https://github.com/samsung-cnct/chart-kibana
maintainers:
- name: Samsung CNCT
  email: samsung.cloudnative@gmail.com
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
