apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.app}}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range .Values.service.annotations }}
    {{ .key }}: "{{ .value }}"
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{.Values.component}}
  ports:
    - name: http
      port: {{.Values.port}}
      protocol: TCP
