{{- if .Values.ingress.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-kibana-auth
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-central
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
type: Opaque
data:
  auth: {{ .Values.ingress.auth | b64enc | quote }}
{{- end }}